version: '3.8'

services:
  node:
    image: node:16-alpine
    restart: always
    working_dir: /app
    command: >
      sh -c "mkdir -p config && cp -r /app_source/config/* /app/config/ && npm ci --production && node index.js"
    environment:
      - NODE_ID=${NODE_ID:-auto}
      - PORT=3000
      - NODE_ENV=production
      - PUBLIC_URL=https://node${NODE_ID}.${DOMAIN_NAME}
      - DISCOVERY_SERVICE=https://discovery.${DOMAIN_NAME}
      - AUTO_REGISTER=true
      - ADMIN_API_KEY=${ADMIN_API_KEY:-changeme}
      - SEED_NODES=${SEED_NODES:-https://node1.${DOMAIN_NAME}}
      - BLOCK_INTERVAL=${BLOCK_INTERVAL:-86400}
    volumes:
      - ./:/app_source  # Mount source files to a different location
      - ./config:/app/config  # Explicitly mount config directory
      - node_data:/app/blocks
      - node_config:/app/config
      - node_modules:/app/node_modules
      - ./index.js:/app/index.js  # Explicitly mount index.js
      - ./package.json:/app/package.json  # Explicitly mount package.json
      - ./blockchain:/app/blockchain  # Explicitly mount blockchain directory
      - ./credit:/app/credit  # Explicitly mount credit directory
      - ./services:/app/services  # Explicitly mount services directory
    networks:
      - certchain_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node${NODE_ID}.rule=Host(`node${NODE_ID}.${DOMAIN_NAME}`)"
      - "traefik.http.routers.node${NODE_ID}.entrypoints=websecure"
      - "traefik.http.routers.node${NODE_ID}.tls=true"
      - "traefik.http.routers.node${NODE_ID}.tls.certresolver=le"
      - "traefik.http.services.node${NODE_ID}.loadbalancer.server.port=3000"

networks:
  certchain_network:
    external: ${EXTERNAL_NETWORK:-false}
    name: ${NETWORK_NAME:-certchain_network}

volumes:
  node_data:
  node_config:
  node_modules:
